-- MariaDB

select sum(AMOUNT) as AMOUNT_EUR, TRANSACTION_DATE from
(
select * from PAYMENTS
where PAYMENTS.CURRENCY=111
UNION
select p.USER_ID_SENDER,
	p.CONTRACT_ID,
       	p.AMOUNT * cr.EXCHANGE_RATE_TO_EUR as AMOUNT,
       	p.CURRENCY, 
	p.TRANSACTION_DATE
from PAYMENTS p
join CURRENCY_RATES cr
on p.TRANSACTION_DATE=cr.EXCHANGE_DATE
where p.CURRENCY!=111 and p.CURRENCY=cr.CURRENCY_ID
) as p 
where USER_ID_SENDER NOT IN (
	select USER_ID from BLACKLIST
	where BLACKLIST_END_DATE IS NULL or BLACKLIST_END_DATE<=CURRENT_DATE()
	)
	and
	CURRENCY NOT IN (
		select CURRENCY_ID from CURRENCIES
		where END_DATE IS NOT NULL and END_DATE<=CURRENT_DATE()
	)
group by TRANSACTION_DATE
order by TRANSACTION_DATE ASC;
